import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import AppSidebar from '@/components/layout/AppSidebar';
import { PostProvider } from '@/components/providers/PostsStoreProvider';
import { fetchPosts } from '@/lib/api';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const posts = await fetchPosts();

  return (
    <html
      lang='ko'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='flex min-h-full flex-col'>
        <SidebarProvider>
          <AppSidebar />
          <main className='flex flex-1 flex-col'>
            <div className='p-3'>
              <SidebarTrigger />
            </div>
            <PostProvider posts={posts}>
              <div className='p-5'>{children}</div>
            </PostProvider>
          </main>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
